package com.xafdy.model;

import java.util.Date;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.record_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Date recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.amount
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.leave
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Double leave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.absenteeism
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Double absenteeism;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.vacation
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Double vacation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.real_amount
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Double realAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    
    private String userName;
    
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.user_id
     *
     * @return the value of attendance.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.user_id
     *
     * @param userId the value for attendance.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.record_date
     *
     * @return the value of attendance.record_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.record_date
     *
     * @param recordDate the value for attendance.record_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.amount
     *
     * @return the value of attendance.amount
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.amount
     *
     * @param amount the value for attendance.amount
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.leave
     *
     * @return the value of attendance.leave
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Double getLeave() {
        return leave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.leave
     *
     * @param leave the value for attendance.leave
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setLeave(Double leave) {
        this.leave = leave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.absenteeism
     *
     * @return the value of attendance.absenteeism
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Double getAbsenteeism() {
        return absenteeism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.absenteeism
     *
     * @param absenteeism the value for attendance.absenteeism
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setAbsenteeism(Double absenteeism) {
        this.absenteeism = absenteeism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.vacation
     *
     * @return the value of attendance.vacation
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Double getVacation() {
        return vacation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.vacation
     *
     * @param vacation the value for attendance.vacation
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setVacation(Double vacation) {
        this.vacation = vacation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.real_amount
     *
     * @return the value of attendance.real_amount
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Double getRealAmount() {
        return realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.real_amount
     *
     * @param realAmount the value for attendance.real_amount
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setRealAmount(Double realAmount) {
        this.realAmount = realAmount;
    }
}