package com.xafdy.model;

public class Education {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.id
     *
     * @return the value of education.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.id
     *
     * @param id the value for education.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.name
     *
     * @return the value of education.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.name
     *
     * @param name the value for education.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}