package com.xafdy.model;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.start_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.budget
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Double budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private String content;
    
    private String start;
    
    private String end;
    
    public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.start_date
     *
     * @return the value of project.start_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.start_date
     *
     * @param startDate the value for project.start_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end_date
     *
     * @return the value of project.end_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end_date
     *
     * @param endDate the value for project.end_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.budget
     *
     * @return the value of project.budget
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Double getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.budget
     *
     * @param budget the value for project.budget
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setBudget(Double budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.content
     *
     * @return the value of project.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.content
     *
     * @param content the value for project.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}