package com.xafdy.model;

import java.util.Date;

public class UserSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.start_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.end_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.position
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    private String content;
    
    private String userName;
    
    private String start;
    
    private String end;
    
    public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.id
     *
     * @return the value of user_schedule.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    
    public Integer getId() {
        return id;
    }

    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.id
     *
     * @param id the value for user_schedule.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.start_date
     *
     * @return the value of user_schedule.start_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.start_date
     *
     * @param startDate the value for user_schedule.start_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.end_date
     *
     * @return the value of user_schedule.end_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.end_date
     *
     * @param endDate the value for user_schedule.end_date
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.position
     *
     * @return the value of user_schedule.position
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.position
     *
     * @param position the value for user_schedule.position
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.user_id
     *
     * @return the value of user_schedule.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.user_id
     *
     * @param userId the value for user_schedule.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.content
     *
     * @return the value of user_schedule.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.content
     *
     * @param content the value for user_schedule.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}